"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-driven settings (issue #22)
# ----------------------------------------
# Every environment-specific value below comes from the process environment,
# with a safe default for a totally unconfigured checkout. Local dev: copy
# `.env.example` to `.env` and run `uv run --env-file .env <command>` (or set
# nothing at all and get dev-friendly defaults). Production: `deploy/app.env`
# (#16) via systemd `EnvironmentFile=`.
def _env_bool(name, default=False):
    """Read an env var as a bool: "1"/"true"/"yes" (case-insensitive) = True."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes')


def _env_list(name, default=()):
    """Read a comma-separated env var into a trimmed list; unset -> default."""
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


# `DJANGO_DEBUG` absent entirely means "nobody has configured this checkout" —
# keep every default permissive (dev-friendly), which is what lets `uv run
# pytest` / CI and a bare `git clone` work with zero env vars, and is what the
# issue's own Goal ("a fresh checkout runs locally with no env file") and its
# "settings import with no env set" test both require. `DJANGO_DEBUG`
# explicitly set (almost always to `false`, from `deploy/app.env`, #16) is
# read as a deliberate declaration of a production-like environment, and is
# what actually switches on the hardened posture below (mandatory
# `SECRET_KEY`, secure cookies, SSL redirect) — not the bare `DEBUG` value by
# itself. A literal "trigger on DEBUG == False" reading can't work: `DEBUG`
# defaults to `False` per this same issue, so every test that doesn't pass
# `secure=True` would start failing (`SECURE_SSL_REDIRECT`), and `uv run
# pytest with no .env` would abort on the missing `SECRET_KEY` before a
# single test ran. See the #22 issue comment for the full reasoning.
_DEBUG_IS_CONFIGURED = 'DJANGO_DEBUG' in os.environ
DEBUG = _env_bool('DJANGO_DEBUG', default=False)
PRODUCTION = _DEBUG_IS_CONFIGURED and not DEBUG

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if PRODUCTION:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY is required when DJANGO_DEBUG=false.'
        )
    # Fine for local dev/tests only — never reaches a deployment where
    # DJANGO_DEBUG=false, which is enforced by the raise above.
    SECRET_KEY = 'django-insecure-dev-only-qp8fzffn^p#8b1=#mw!cgfs^xwvvv1do'

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# The login form (and every POST) must work behind Nginx terminating TLS
# (#16). Either set DJANGO_CSRF_TRUSTED_ORIGINS explicitly, or it is derived
# from ALLOWED_HOSTS (each host prefixed https://).
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS') or [
    f'https://{host}' for host in ALLOWED_HOSTS
]

if PRODUCTION:
    # Nginx terminates TLS and forwards the original scheme in this header
    # (#16); trust it so Django knows the request was actually HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'auctions',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model. Set from the outset so auth/admin migrations bind to it on a
# fresh database. Switching an existing install requires deleting db.sqlite3
# first (see README) — Django refuses to swap the user model after auth/admin
# migrations have run.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Login is enforced project-wide here (Django 5.1+). Every view requires an
    # authenticated user unless decorated with ``login_not_required`` (only the
    # login page is — see config/urls.py). This is the access gate #12–#14 rely
    # on; see _docs/access-convention.md.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Authentication redirects (issue #11)
# ------------------------------------
# LOGIN_URL is where LoginRequiredMiddleware sends anonymous requests.
# LOGIN_REDIRECT_URL is the post-login landing page (the home view at ``/``).
# LOGOUT_REDIRECT_URL sends a logged-out user back to the login page.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Required for `collectstatic` (used by deploy/deploy.sh, #16) — Nginx's
# `templates/nginx.conf` serves `/static/` as `alias $APP_DIR/staticfiles/`,
# i.e. exactly this path when APP_DIR is the deploy checkout root.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Notification email dispatch (issue #9)
# --------------------------------------
# ``auctions.notifications.dispatch_pending`` turns pending Notification rows
# into email. The provider is swappable: NOTIFICATION_BACKEND is a dotted path
# to a class in ``auctions.email`` implementing ``send(to, subject, body)``.
# The console backend (the default) prints to stdout; ``ResendBackend`` POSTs to
# the Resend HTTP API and needs RESEND_API_KEY / RESEND_FROM. Secrets come from
# the environment, never the repo. (#22 will generalise env-driven settings;
# these are added in the same os.environ style as the IZSOLES_* block below.)
NOTIFICATION_BACKEND = os.environ.get(
    'NOTIFICATION_BACKEND', 'auctions.email.ConsoleBackend'
)
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
RESEND_FROM = os.environ.get('RESEND_FROM', '')

# Public URL of a single listing, used in notification emails. ``{source_id}``
# is replaced with the listing's izsoles UUID. Default points at the live
# izsoles detail page (``/izsole/<uuid>``); override once a local detail view
# exists (#12).
LISTING_URL_TEMPLATE = os.environ.get(
    'LISTING_URL_TEMPLATE', 'https://izsoles.ta.gov.lv/izsole/{source_id}'
)


# izsoles.csv ingest (issue #4)
# ----------------------------
# An operator drops the daily ``izsoles.csv`` at IZSOLES_CSV_PATH; the parser
# (auctions.ingest.parse) reads it from there. The httpx fetcher
# (auctions.ingest.fetch) is a best-effort secondary path that refreshes that
# same local file from the open-data URL.
IZSOLES_CSV_PATH = os.environ.get(
    'IZSOLES_CSV_PATH', str(BASE_DIR / 'data' / 'izsoles.csv')
)
IZSOLES_OPEN_DATA_URL = os.environ.get(
    'IZSOLES_OPEN_DATA_URL', 'https://izsoles.ta.gov.lv/open_data/izsoles.csv'
)
# Optional ``Cookie:`` header value for the fetch (live session cookies from a
# logged-in browser); the open-data endpoint 403s without them.
IZSOLES_FETCH_COOKIE = os.environ.get('IZSOLES_FETCH_COOKIE', '')


# Logging (issue #10)
# --------------------
# Nothing configured logging before this. Django's own default only attaches
# handlers under the "django" logger tree (request/server/security), so an
# INFO-level ``logging.getLogger(__name__)`` call from a management command
# (e.g. ``run_daily_import``) had no handler to reach and was silently
# dropped when run standalone (as cron would run it). This adds one console
# handler at INFO on the root logger — minimal, and additive: it doesn't
# touch Django's own logger configuration (``disable_existing_loggers`` stays
# ``False``), it just gives every other logger in the project a place to go.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
