# Generated by Django 6.1 on 2026-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('initiated_by', models.CharField(max_length=10)),
                ('bailiff', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('state', models.CharField(max_length=100)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('office_id', models.CharField(blank=True, max_length=50)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bid_step', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('raw_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
